server:
  port: ${SERVER_PORT:8080}
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: redis-cache-demo
springdoc:
  api-docs:
    path: /api-docs